### ISSUE TITLE
Reorganizar a página de impacto

### ISSUE THREAD

**Issue by igordsm** [Insper/dev-aberto#127]
A [página de impacto](https://insper.github.io/dev-aberto/impacto/) tem uma organização estranha. Reorganizá-la em torno de projetos seria muito mais interessante. Exemplo abaixo:

# Pandas
## PRs aceitos
- link1 
- link 2
## PRs enviados e não aceitos
- link 3
- link 4
## Issues abertas 
- link 5

Eventualmente farei isto, mas se tivesse para este ano seria muito bom.

**Comment by aleblucher** [comment]
Planejo trabalhar nesse issue.

**Comment by igordsm** [comment]
Closed by #137
