### ISSUE TITLE
Issues de sala de aula 2020/1

### ISSUE THREAD

**Issue by igordsm** [Insper/dev-aberto#198]
Registrem aqui as issues escolhidas e marquem seu grupo.

**Comment by brunoartc** [comment]
@franciol @Otofuji Terminal 2 [#271](https://github.com/elementary/terminal/issues/271)

**Comment by elijose55** [comment]
@elijose55 @pedrooa Pydash [#136](https://github.com/dgilland/pydash/issues/136)

**Comment by gabrielvf1** [comment]
@gabrielvf1 @veronur Pandas https://github.com/pandas-dev/pandas/issues/11136

**Comment by IsabellaRO** [comment]
@isabellaRO @hugosoftdev Elementary [#552](https://github.com/elementary/music/issues/552)

**Comment by SabrinaSimao** [comment]
Sabrina, @pedrodelapena e Jean
BTRoblox 
https://github.com/AntiBoomz/BTRoblox/issues/14

**Comment by raphacosta27** [comment]
@raphacosta27 @gabsmoreira  Pandas #32073

**Comment by raphacosta27** [comment]
@raphacosta27 @gabsmoreira Pandas https://github.com/pandas-dev/pandas/issues/32073#issue-566759926

**Comment by igordsm** [comment]
Usarei como exemplo na próxima aula a issue https://github.com/elementary/files/issues/1227
