### ISSUE TITLE
Temas de apresentação

### ISSUE THREAD

**Issue by igordsm** [Insper/dev-aberto#264]
Responder aqui com o grupo de vocês e a data pretendida.

**Comment by SabrinaSimao** [comment]
Sabrina/Jean/Pedro - obsolescencia programada

**Comment by Veronur** [comment]
Lucca e Francato - Common Clause

**Comment by BrunaKimura** [comment]
Bruna e Martim - "Ethical Software" - 08/06

**Comment by franciol** [comment]
Eric, Francisco, Isabella - "retas FLOSS 3: Comportamento de Linus Torvalds e codigos de conduta no kernel do Linux
TiVo e GPLv3"  - 08/06

**Comment by VictorLMoura** [comment]
Richard Stallman renuncia da Free Software Foundation
Victor Laperuta, Eli Jose e Pedro Azambuja

**Comment by hugosoftdev** [comment]
Hugo e Isa 
https://medium.com/holochain/understanding-the-cryptographic-autonomy-license-172ac920966d
08/06

**Comment by raphacosta27** [comment]
> Eric, Francisco, Bruno Arthur - "retas FLOSS 3: Comportamento de Linus Torvalds e codigos de conduta no kernel do Linux
> TiVo e GPLv3" - 08/06

Vocês pegaram dois temas?

**Comment by franciol** [comment]
> > Eric, Francisco, Bruno Arthur - "retas FLOSS 3: Comportamento de Linus Torvalds e codigos de conduta no kernel do Linux
> > TiVo e GPLv3" - 08/06
> 
> Vocês pegaram dois temas?

Opa, acho q no ctrl+c ctrl+v eu acabei pegando o tema de baixo tambem. O tema mesmo é o do codigo de conduta.

**Comment by raphacosta27** [comment]
> > > Eric, Francisco, Bruno Arthur - "retas FLOSS 3: Comportamento de Linus Torvalds e codigos de conduta no kernel do Linux
> > > TiVo e GPLv3" - 08/06
> > 
> > 
> > Vocês pegaram dois temas?
> 
> Opa, acho q no ctrl+c ctrl+v eu acabei pegando o tema de baixo tambem. O tema mesmo é o do codigo de conduta.

Opa, beleza, valeu pela resposta rápida Chicão.

**Comment by raphacosta27** [comment]
Tretas FLOSS 2: Eric Saymond é expulso da Open Source initiative
Raphael e Gabriel
03/06
