### ISSUE TITLE
Apresentações Aula 02

### ISSUE THREAD

**Issue by igordsm** [Insper/dev-aberto#323]
Comentem aqui os grupos e de qual software irão falar. A ordem de chegada importa, então se der empate ganha quem postar primeiro.

**Comment by brunoacpcosta** [comment]
Docker - Bruno Costa, Gustavo Gobetti, Vitor Satyro

**Comment by RaphaelAzev** [comment]
GoDot- Raphael Azevedo, Luca Farah, Gabriel Scodiero

**Comment by pedr0luiz** [comment]
@VFermat @pedr0luiz @gabrielzezze - Kubernetes

**Comment by gabrielnoal** [comment]
[KDE](https://kde.org/pt-br/) - Eu, @WarlenRodrigues e @manucirne

**Comment by CaioFauza** [comment]
flatpak - Caio Fauza, Gustavo Braga e Leonardo Mendes
