### ISSUE TITLE
Issues de sala de aula

### ISSUE THREAD

**Issue by igordsm** [Insper/dev-aberto#45]
Comentem aqui o que vocês querem mexer. Assim evitamos trabalho dobrado  e combinamos o que cada um irá fazer.

@LiuSeeker @elisamalzoni @Samuelgranato @ViniGl @guipleite @hugoecarl @gabriellm1 @Alexandreae @aleblucher @GiuPassarelli @antonioandraues @lucassa3 @gabrielvr @pedrocunial

**Comment by AntonioAndraues** [comment]
Faremos o issue de formatação de índice 2 -> recomendado no pdf da aula
@ViniGl  @Samuelgranato  @AntonioAndraues
https://github.com/pandas-dev/pandas/issues/13257

**Comment by gabriellm1** [comment]
Faremos o issue de pré-processamento 3 (pdf da aula)
@gabriellm1 @guipleite @hugoecarl 
pandas-dev/pandas#16698

**Comment by elisamalzoni** [comment]
https://github.com/pandas-dev/pandas/issues/27563

@Leostayner @elisamalzoni

**Comment by Alexandreae** [comment]
Faremos o issue de pré-processamento 2 (pdf da aula)
@Alexandreae @GiuPassarelli 
pandas-dev/pandas#18198

**Comment by aleblucher** [comment]
@aleblucher  @LiuSeeker 
pandas-dev/pandas#13628

**Comment by Alexandreae** [comment]
@Alexandreae @GiuPassarelli
pandas-dev/pandas#16300

**Comment by igordsm** [comment]
Pessoal, irei usar o bug https://github.com/pandas-dev/pandas/issues/14119 como exemplo na próxima aula. Faremos, juntos, o processo de encontrar exatamente onde mexer no código. O resultado disso será uma lista de ferramentas e estratégias que vocês podem replicar no bug de vocês.

@Alexandreae @aleblucher @pedrocunial @lucassa3 @ViniGl @AntonioAndraues @leostayner @GiuPassarelli @LiuSeeker @elisamalzoni @Samuelgranato @gabriellm1 @hugoecarl @guipleite

**Comment by pedrocunial** [comment]
https://github.com/pandas-dev/pandas/issues/19082

O @GabrielValeRios , @lucassa3 e eu faremos esse!

:shipit:

**Comment by hugoecarl** [comment]
> Faremos o issue de pré-processamento 3 (pdf da aula)
> @gabriellm1 @guipleite @hugoecarl
> [pandas-dev/pandas#16698](https://github.com/pandas-dev/pandas/issues/16698)

Mudamos para https://github.com/pandas-dev/pandas/issues/25955
