### ISSUE TITLE
Apresentação sobre cultura livre

### ISSUE THREAD

**Issue by fbarth** [Insper/dev-aberto#665]
Registre neste issue o tema da equipe e os integrantes da equipe. Um registro por equipe.

**Comment by Eikinho** [comment]
Tema: GitHub Copilot é ético? Respeita licenças de software

Data Apresentação: 17/11/2022

Grupo: Eiki Yamashiro e Marcelo Miguel

**Comment by guishas** [comment]
Telemetria é "ético"? 

Data apresentação: 22/11

Grupo: Guilherme Lunetta, Rafael Monteiro e João Magalhães

**Comment by keiyanishio** [comment]
Regulamentações recentes na Europa sobre durabilidade de smartphones (bateria, right to repair, etc).

Data apresentação: 24/11

Grupo: Keiya Nishio e Bruno Freitas

**Comment by gabrielztk** [comment]
Regulamentações futuras na Europa sobre responsabilidade legal dos criadores de IAs

Data apresentação: 22/11

Grupo: Luiza Silvera, Guilherme Batista e Gabriel Zanetti

**Comment by slimkaki** [comment]
Tema: The new open-source economics (Yochai Benkler, 2005). O que mudou de 2005
para 2022?
Data da Apresentação: 29/11
Grupo: João Pedro Meirelles, Gustavo Molina e Rafael Almada

**Comment by jonathansutton1** [comment]
**Tema:** Mantainer burnout

**Data da Apresentação:** 24/11/2022

**Grupo:** Cesar Ades e Jonathan Sutton

**Comment by felipebpl** [comment]
Tema: A relação entre Software as a Service (SaaS) e projetos de Código Aberto

Data da Apresentação: 17/11/2022

Grupo: Caroline Chaim, Felipe Lemos, João Farias Araujo

**Comment by Lahiry** [comment]
Tema: Por que Open Source é crítico para criptomoedas?

Data da Apresentação: 24/11/2022

Grupo: Paulo Kim, Raphael Lahiry e Rodrigo Coelho

**Comment by fbarth** [comment]
Todos os alunos com projetos e datas de apresentação definidos.
